<?php
/**
 * Copyright 2008 Chris Abernethy
 *
 * This file is part of User Voice.
 * 
 * User Voice is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * User Voice is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with User Voice.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
?>
<p><?php echo wp_specialchars($this->get('current_state_message')) ?></p>
<p><label class="selectit"><input style="vertical-align:middle;" name="<?php echo attribute_escape($this->get('plugin_label') . '_visibility') ?>" type="radio" value="public" <?php echo 'public' == $this->get('visibility') ? 'checked="checked"' : '' ?>/> <?php echo wp_specialchars(__('Ignore the default settings and make this page visible to everyone', 'user-voice')) ?></label></p>
<p><label class="selectit"><input style="vertical-align:middle;" name="<?php echo attribute_escape($this->get('plugin_label') . '_visibility') ?>" type="radio" value="private" <?php echo 'private' == $this->get('visibility') ? 'checked="checked"' : '' ?>/> <?php echo wp_specialchars(__('Ignore the default settings and make this page visible only to members', 'user-voice')) ?></label></p>
<p><label class="selectit"><input style="vertical-align:middle;" name="<?php echo attribute_escape($this->get('plugin_label') . '_visibility') ?>" type="radio" value="default" <?php echo 'default' == $this->get('visibility') ? 'checked="checked"' : '' ?>/> <?php echo wp_specialchars(__('Honor the default page visibility settings', 'user-voice')) ?></label></p>
