<?php
/**
 * Copyright 2008 Chris Abernethy
 *
 * This file is part of User Voice.
 * 
 * User Voice is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * User Voice is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with User Voice.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
?>
<script src="http://<?php echo attribute_escape($this->get('username')) ?>.uservoice.com/pages/<?php echo attribute_escape($this->get('slug')) ?>/widgets/tab.js?alignment=<?php echo attribute_escape($this->get('alignment')) ?>&amp;color=<?php echo attribute_escape($this->get('color')) ?>" type="text/javascript"></script>
